# Generated by Django 4.2.2 on 2023-06-20 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_notes_delete_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='author',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
